'use strict';

/**
 * tests/m8/m8.4/_helpers.js — shared fixture helpers for M8.4 update tests.
 *
 * Strategy
 * --------
 * Each test:
 *   1. mkProject() — builds a sandbox by running real `kaizen init` in a
 *      tmp dir so `.kaizen-dvir/manifest.json` is the v1.5.0-rc.0 baseline
 *      and the Yotzer cell + skills are on disk.
 *   2. mkCanonical(opts) — builds a SEPARATE canonical tree (sibling tmp
 *      dir) by copying the just-init'd project's `.kaizen-dvir/` and
 *      `bin/` and `.claude/settings.json` etc., then optionally mutates
 *      the bundled `celula.yaml` (rename agent / drop agent / add agent)
 *      and refreshes its manifest.json + version.
 *   3. runUpdateInProc() — invokes `kaizen-update.runUpdate()` in-process
 *      with stdout/stderr capture and KAIZEN_PROJECT_ROOT pointing at the
 *      sandbox. Mirrors the M6.2 test runner.
 *
 * The "rename agent" mutation is the cleanest version-bump simulation:
 *   - tier_3 lists `risk-mapper` in v1 → renames to `gap-finder` in v2.
 *   - copies `agents/risk-mapper.md` to `agents/gap-finder.md`.
 *   - keeps `risk-mapper.md` on disk in canonical (so the L2 overwrite
 *     is preserved) BUT removes it from `celula.yaml`.
 *   - canonical manifest re-hashes celula.yaml.
 * After update: skills directory must contain `gap-finder.md` (new) and
 * the helper warns about `risk-mapper.md` being orphaned in the project.
 */

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');

const SOURCE_ROOT = path.resolve(__dirname, '..', '..', '..');
const CLI = path.join(SOURCE_ROOT, 'bin', 'kaizen.js');
const UPDATE_BIN = path.join(SOURCE_ROOT, 'bin', 'kaizen-update.js');

function mkTmp(label) {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'kaizen-m8.4-' + label + '-'));
}

function rmTmp(dir) {
  if (!dir) return;
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch (_) {
    // best-effort cleanup
  }
}

function sha256(buf) {
  return 'sha256:' + crypto.createHash('sha256').update(buf).digest('hex');
}

function fileExists(abs) {
  try {
    return fs.statSync(abs).isFile();
  } catch (_) {
    return false;
  }
}

function listDirFiles(abs) {
  try {
    return fs
      .readdirSync(abs, { withFileTypes: true })
      .filter((e) => e.isFile())
      .map((e) => e.name)
      .sort();
  } catch (_) {
    return [];
  }
}

/**
 * Walk a directory tree and return relative POSIX-style paths of every file.
 */
function walkFiles(rootDir, relDir, out) {
  out = out || [];
  relDir = relDir || '';
  const here = path.join(rootDir, relDir);
  let entries;
  try {
    entries = fs.readdirSync(here, { withFileTypes: true });
  } catch (_) {
    return out;
  }
  for (const e of entries) {
    const childRel = relDir ? relDir + '/' + e.name : e.name;
    if (e.isDirectory()) {
      walkFiles(rootDir, childRel, out);
    } else if (e.isFile()) {
      out.push(childRel);
    }
  }
  return out;
}

/**
 * Copy a directory tree recursively. Source must exist; dest is created.
 */
function copyTree(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const files = walkFiles(src);
  for (const rel of files) {
    const srcAbs = path.join(src, rel.split('/').join(path.sep));
    const destAbs = path.join(dest, rel.split('/').join(path.sep));
    fs.mkdirSync(path.dirname(destAbs), { recursive: true });
    fs.copyFileSync(srcAbs, destAbs);
  }
}

/**
 * Build a sandbox project at v1.5.0-rc.0 by running real `kaizen init`.
 * Returns the absolute project root.
 */
function mkProject(label) {
  const project = mkTmp('proj-' + label);
  const result = spawnSync(process.execPath, [CLI, 'init'], {
    cwd: project,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error(
      'mkProject: kaizen init failed; status=' + result.status +
        ' stderr=' + result.stderr
    );
  }
  // `kaizen init` does not write `.kaizen-dvir/manifest.json` into the
  // project (the manifest is an L1 build artifact regenerated by
  // `npm pack`). The update orchestrator needs a local manifest to read
  // from, so we copy SOURCE_ROOT's canonical manifest into the project
  // and backdate the version to 1.4.0. This puts the sandbox into the
  // exact state a real expert would be in: just-installed v1.4.0,
  // about to update to v1.5.0.
  const sourceManifestPath = path.join(
    SOURCE_ROOT, '.kaizen-dvir', 'manifest.json'
  );
  const manifestPath = path.join(project, '.kaizen-dvir', 'manifest.json');
  const m = JSON.parse(fs.readFileSync(sourceManifestPath, 'utf8'));
  m.version = '1.4.0';
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  fs.writeFileSync(manifestPath, JSON.stringify(m, null, 2) + '\n', 'utf8');
  return project;
}

/**
 * Build a canonical tree at v1.5.0 by copying SOURCE_ROOT's framework
 * payload (the very same tree that `npm pack` would ship) and then
 * applying optional mutations.
 *
 * @param {object} opts
 * @param {string} opts.label                   tmp-dir suffix for clarity
 * @param {string} [opts.toVersion='1.5.0']     version to stamp in manifest
 * @param {function(string):void} [opts.mutateCellManifest]
 *   Receives the absolute path of the bundled celula.yaml; may rewrite it.
 * @param {function(string):void} [opts.mutateCellTree]
 *   Receives the absolute path of the cell root; may add/rename/remove
 *   agent files etc.
 */
function mkCanonical(opts) {
  opts = opts || {};
  const label = opts.label || 'canon';
  const toVersion = opts.toVersion || '1.5.0';
  const canonical = mkTmp('canon-' + label);

  // Mirror the package `files` whitelist into the canonical tree. We copy
  // the directories needed for the layered policy walk + the bundled cell.
  const PAYLOAD = [
    'bin',
    '.kaizen-dvir/dvir',
    '.kaizen-dvir/celulas',
    '.kaizen-dvir/instructions',
    '.kaizen-dvir/infra',
    '.kaizen-dvir/refs',
    '.kaizen-dvir/commandments.md',
    '.kaizen-dvir/dvir-config.yaml',
    '.kaizen-dvir/manifest.json',
    '.claude/settings.json',
    '.claude/README.md',
    'package.json',
    '.gitignore',
  ];
  for (const rel of PAYLOAD) {
    const srcAbs = path.join(SOURCE_ROOT, rel);
    const destAbs = path.join(canonical, rel);
    if (!fs.existsSync(srcAbs)) continue;
    const stat = fs.statSync(srcAbs);
    if (stat.isDirectory()) {
      copyTree(srcAbs, destAbs);
    } else {
      fs.mkdirSync(path.dirname(destAbs), { recursive: true });
      fs.copyFileSync(srcAbs, destAbs);
    }
  }

  // Apply mutations to the bundled cell BEFORE refreshing the manifest.
  const cellRoot = path.join(canonical, '.kaizen-dvir', 'celulas', 'yotzer');
  const cellManifest = path.join(cellRoot, 'celula.yaml');
  if (typeof opts.mutateCellTree === 'function') {
    opts.mutateCellTree(cellRoot);
  }
  if (typeof opts.mutateCellManifest === 'function') {
    opts.mutateCellManifest(cellManifest);
  }

  // Stamp the manifest with the target version + refresh hashes for any
  // file the layered policy will compare against (we keep simple — only
  // bump version; M6.2 update path re-resolves hashes from local files
  // anyway). We DO need to add/refresh entries for cell files we mutated
  // so the layered policy walk transports them as L2 overwrites.
  const manifestPath = path.join(canonical, '.kaizen-dvir', 'manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.version = toVersion;

  // Refresh hashes for ALL agents/* files under the cell + the celula.yaml
  // (anything that may have been mutated). We do not enumerate every file
  // — only entries already present in the manifest get refreshed.
  const cellRel = '.kaizen-dvir/celulas/yotzer';
  for (const rel of Object.keys(manifest.files)) {
    if (!rel.startsWith(cellRel + '/')) continue;
    const abs = path.join(canonical, rel.split('/').join(path.sep));
    if (!fs.existsSync(abs)) {
      // File removed in canonical (e.g., dropped agent persona). Drop the
      // manifest entry so the layered policy does not seek a missing file.
      delete manifest.files[rel];
      continue;
    }
    const buf = fs.readFileSync(abs);
    manifest.files[rel] = {
      hash: sha256(buf),
      layer: manifest.files[rel].layer,
      size: buf.length,
    };
  }

  // If mutateCellTree added new files, register them in the manifest as L2
  // (matches existing cell files). Walk current cell dir and union.
  const onDiskCellFiles = walkFiles(cellRoot).map(
    (rel) => cellRel + '/' + rel
  );
  for (const rel of onDiskCellFiles) {
    if (manifest.files[rel]) continue;
    const abs = path.join(canonical, rel.split('/').join(path.sep));
    const buf = fs.readFileSync(abs);
    manifest.files[rel] = {
      hash: sha256(buf),
      layer: 'L2',
      size: buf.length,
    };
  }

  manifest.generatedAt = new Date().toISOString();
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  return canonical;
}

/**
 * Run kaizen-update.runUpdate() in-process. Captures stdout/stderr and
 * returns { exitCode, stdout, stderr }.
 */
function runUpdateInProc(args, projectRoot) {
  delete require.cache[require.resolve(UPDATE_BIN)];
  const { runUpdate } = require(UPDATE_BIN);
  const stdout = [];
  const stderr = [];
  const origStdoutWrite = process.stdout.write.bind(process.stdout);
  const origStderrWrite = process.stderr.write.bind(process.stderr);
  process.stdout.write = (s) => {
    stdout.push(typeof s === 'string' ? s : s.toString());
    return true;
  };
  process.stderr.write = (s) => {
    stderr.push(typeof s === 'string' ? s : s.toString());
    return true;
  };
  const origCwd = process.cwd();
  const origEnv = process.env.KAIZEN_PROJECT_ROOT;
  process.env.KAIZEN_PROJECT_ROOT = projectRoot;
  let exitCode;
  try {
    exitCode = runUpdate(args);
  } finally {
    process.stdout.write = origStdoutWrite;
    process.stderr.write = origStderrWrite;
    if (origEnv === undefined) delete process.env.KAIZEN_PROJECT_ROOT;
    else process.env.KAIZEN_PROJECT_ROOT = origEnv;
    process.chdir(origCwd);
  }
  return {
    exitCode: exitCode,
    stdout: stdout.join(''),
    stderr: stderr.join(''),
  };
}

/**
 * Snapshot every .md under .claude/commands/Kaizen/ recursively. Returns a
 * map { relPath: { sha256, mtimeMs, size } } — same shape as the M8.3
 * idempotency snapshot helper.
 */
function snapshotSkills(targetRoot) {
  const skillsRoot = path.join(targetRoot, '.claude', 'commands', 'Kaizen');
  const out = {};
  const files = walkFiles(skillsRoot);
  for (const rel of files) {
    const abs = path.join(skillsRoot, rel.split('/').join(path.sep));
    const stat = fs.statSync(abs);
    const content = fs.readFileSync(abs);
    out[rel] = {
      mtimeMs: stat.mtimeMs,
      size: stat.size,
      sha: crypto.createHash('sha256').update(content).digest('hex'),
    };
  }
  return out;
}

module.exports = {
  SOURCE_ROOT,
  CLI,
  UPDATE_BIN,
  mkTmp,
  rmTmp,
  mkProject,
  mkCanonical,
  runUpdateInProc,
  fileExists,
  listDirFiles,
  walkFiles,
  copyTree,
  sha256,
  snapshotSkills,
};
